apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:xxxxxxx/xxxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
spec:
  selector:
    name: app
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 80
